// FPGA top-level wrapper targeting the Digilent Cmod A7-35T. Connects the
// TTA core's instruction bus to on-chip block RAM (boot/program memory) and
// its data bus to external SRAM pins.
//
// Memory map:
//   Instruction bus → blkram (12288 words, preloaded from bootmem.mem)
//   Data bus        → external SRAM via directly-bridged I/O pins
module cmod_a35t_top (
    input wire rst_i,                   // Active-high synchronous reset
    input wire sysclk_i,               // System clock

    // External SRAM interface (directly bridged from data_bus)
    input logic [DATA_WIDTH-1:0] sram_data_i,    // SRAM read data (36-bit tagged)
    output logic [DATA_WIDTH-1:0] sram_data_o,   // SRAM write data (36-bit tagged)
    output logic [18:0] sram_addr_o,   // SRAM word address
    output logic sram_valid_o,         // SRAM transaction valid
    output logic [3:0] sram_wstrb_o,   // SRAM per-byte write strobes
    input logic sram_ready_i,          // SRAM ready / acknowledge

    // UART (active pins reserved for future use — currently unconnected)
    /* verilator lint_off UNUSEDSIGNAL */
    input  wire uart_rxd_i,
    /* verilator lint_on UNUSEDSIGNAL */
    /* verilator lint_off UNDRIVEN */
    output wire uart_txd_o
    /* verilator lint_on UNDRIVEN */
);

  // Instruction bus wires (sequencer ↔ blkram)
  wire [3:0]  ibs_wstrb;
  wire [31:0] ibs_write_data;
  wire [31:0] ibs_addr;
  wire        ibs_valid;
  wire        ibs_instr;
  wire        ibs_ready;
  wire [31:0] ibs_read_data;

  // Boot / program memory: 12288 words = 48 KiB, preloaded from a hex file
  // generated by the assembler or external tooling.
  blkram #(
      .INIT_FILE("bootmem.mem"),
      .RAM_DEPTH(12288)
  ) bootmem (
      .clk_i(sysclk_i),
      .rst_i(rst_i),
      .bus_wstrb_i(ibs_wstrb),
      .bus_write_data_i(ibs_write_data),
      .bus_addr_i(ibs_addr),
      .bus_valid_i(ibs_valid),
      .bus_instr_i(ibs_instr),
      .bus_ready_o(ibs_ready),
      .bus_read_data_o(ibs_read_data)
  );

  // Data bus wires (execute ↔ SRAM)
  wire [3:0]  dbs_wstrb;
  wire [DATA_WIDTH-1:0] dbs_write_data;
  /* verilator lint_off UNUSEDSIGNAL */
  wire [31:0] dbs_addr;
  /* verilator lint_on UNUSEDSIGNAL */
  wire        dbs_valid;

  assign sram_data_o  = dbs_write_data;
  assign sram_valid_o = dbs_valid;
  assign sram_wstrb_o = dbs_wstrb;
  assign sram_addr_o  = dbs_addr[18:0];

  tta tta (
      .rst_i(rst_i),
      .clk_i(sysclk_i),
      /* verilator lint_off PINCONNECTEMPTY */
      .instr_done_o(),
      /* verilator lint_on PINCONNECTEMPTY */
      // Instruction bus → blkram
      .instr_wstrb_o(ibs_wstrb),
      .instr_write_data_o(ibs_write_data),
      .instr_addr_o(ibs_addr),
      .instr_valid_o(ibs_valid),
      .instr_instr_o(ibs_instr),
      .instr_ready_i(ibs_ready),
      .instr_read_data_i(ibs_read_data),
      // Data bus → SRAM
      .data_wstrb_o(dbs_wstrb),
      .data_write_data_o(dbs_write_data),
      .data_addr_o(dbs_addr),
      .data_valid_o(dbs_valid),
      /* verilator lint_off PINCONNECTEMPTY */
      .data_instr_o(),
      /* verilator lint_on PINCONNECTEMPTY */
      .data_ready_i(sram_ready_i),
      .data_read_data_i(sram_data_i),
      .mailbox_data_i({DATA_WIDTH{1'b0}}),
      .mailbox_valid_i(1'b0),
      .mailbox_ack_o(),
      .mailbox_out_o(),
      .mailbox_out_valid_o()
  );

endmodule
