// FPGA top-level wrapper targeting the Digilent Cmod A7-35T. Connects the
// TTA core's instruction bus to on-chip block RAM (boot/program memory) and
// its data bus to external SRAM pins.
//
// Memory map:
//   Instruction bus → blkram (12288 words, preloaded from bootmem.mem)
//   Data bus        → external SRAM via directly-bridged I/O pins
module cmod_a35t_top (
    input wire rst_i,                   // Active-high synchronous reset
    input wire sysclk_i,               // System clock

    // External SRAM interface (directly bridged from data_bus)
    input logic [31:0] sram_data_i,    // SRAM read data
    output logic [31:0] sram_data_o,   // SRAM write data
    output logic [18:0] sram_addr_o,   // SRAM word address
    output logic sram_valid_o,         // SRAM transaction valid
    output logic [3:0] sram_wstrb_o,   // SRAM per-byte write strobes
    input logic sram_ready_i,          // SRAM ready / acknowledge

    // UART (active pins reserved for future use — currently unconnected)
    input  wire uart_rxd_i,
    output wire uart_txd_o
);

  bus_if bootmem_bus ();
  // Boot / program memory: 12288 words = 48 KiB, preloaded from a hex file
  // generated by the assembler or external tooling.
  blkram #(
      .INIT_FILE("bootmem.mem"),
      .RAM_DEPTH(12288)
  ) bootmem (
      .clk_i(sysclk_i),
      .rst_i(rst_i),

      .data_bus(bootmem_bus.slave)
  );

  bus_if data_bus ();
  always_comb begin
    // Bridge the core data bus to external SRAM-style pins.
    data_bus.read_data = sram_data_i;
    data_bus.ready = sram_ready_i;
    sram_data_o = data_bus.write_data;
    sram_valid_o = data_bus.valid;
    sram_wstrb_o = data_bus.wstrb;
    sram_addr_o = data_bus.addr;
  end

  tta tta (
      .rst_i(rst_i),
      .clk_i(sysclk_i),
      .instr_bus(bootmem_bus),
      .data_bus(data_bus)
  );

endmodule : cmod_a35t_top
